# Generated by Django 6.1.1 on 2026-09-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
    ]
