# Generated by Django 6.0.5 on 2026-08-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
